version: "3"
services:
  frontend:
    image: mikenewxyz/portfolio:latest
    ports:
      - 3400:3000
    environment:
      REVALIDATE_TOKEN: ${REVALIDATE_TOKEN}
  directus:
    image: directus/directus:10.13.1
    ports:
      - 3401:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: ${SECRET_KEY}
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: d1r3ctu5
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: http://localhost:3000
      EMAIL_FROM: hello@mikenew.xyz
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: smtp-relay.brevo.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: 79c0a7001@smtp-brevo.com
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_KEY}
networks: {}
