import ContextProviderWrapper from "@/context/context-provider-wrapper";
import "./globals.css";
import Background from "@/components/background/background";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="relative overflow-hidden bg-dark text-light">
				<ContextProviderWrapper>{children}</ContextProviderWrapper>

				<Background />
			</body>
		</html>
	);
}
